project_id = "qixukpmsxsynvzugnkxv"

[functions.extract-pdf-units]
verify_jwt = false

[functions.extract-pdf-labels]
verify_jwt = false
wall_clock_timeout = 120

[functions.extract-pdf-unit-types]
verify_jwt = false

[functions.extract-pdf-countertops]
verify_jwt = false

[functions.extract-pdf-cabinets]
verify_jwt = false


